import { Command } from 'commander';
import { Logger } from '../utils/logger';
import { loadStrategy, generateHtmlReport, saveExportFile, loadBlogSnapshot } from '../tasks/report';
import { fetchD1MonitoringReports, fetchBusinessMetrics } from '../utils/d1-client';
import { fetchGA4Data } from '../utils/ga4-client';
import { ReportData } from '../types';

export const reportCommand = new Command('report')
  .description('Generate Management Design Sheet Business Progress Report')
  .action(async () => {
    try {
      Logger.info('Generating Management Design Sheet report...');

      // 1. Load blog snapshot (generated by `npm run summary`, committed to git)
      const snapshot = await loadBlogSnapshot();
      const strategy = await loadStrategy();

      // 2. Fetch D1 data
      const monitoringLogs = await fetchD1MonitoringReports(7);
      const businessMetrics = await fetchBusinessMetrics();

      // 3. Fetch GA4 data
      const ga4Data = await fetchGA4Data(7);

      const criticalCount = monitoringLogs.filter(log => log.severity === 'CRITICAL').length;
      const warningCount = monitoringLogs.filter(log => log.severity === 'WARNING').length;

      // Exclude test data (2 users)
      let remainingToSubtract = 2;
      let adjustedPaidMembers = businessMetrics.paidMembers;
      let adjustedFreeMembers = businessMetrics.freeMembers;

      const subtractFromPaid = Math.min(adjustedPaidMembers, remainingToSubtract);
      adjustedPaidMembers -= subtractFromPaid;
      remainingToSubtract -= subtractFromPaid;

      const subtractFromFree = Math.min(adjustedFreeMembers, remainingToSubtract);
      adjustedFreeMembers -= subtractFromFree;

      const adjustedActiveSubscriptions = Math.max(0, businessMetrics.activeSubscriptions - 2);

      const reportData: ReportData = {
        strategy,
        stats: {
          totalArticles: snapshot.totalArticles,
          last30DaysUpdates: snapshot.last30DaysUpdates,
          lighthouseScore: 100,
          monitoring: {
            criticalCount,
            warningCount,
          },
          business: {
            paidMembers: adjustedPaidMembers,
            freeMembers: adjustedFreeMembers,
            activeSubscriptions: adjustedActiveSubscriptions,
          },
          traffic: {
            pv: ga4Data.screenPageViews,
            uu: ga4Data.activeUsers,
            avgStayTime: ga4Data.avgEngagementTime,
            topPages: ga4Data.topPages,
            weeklyTraffic: ga4Data.weeklyTraffic,
          },
          brand: {
            avgEngagementTime: ga4Data.avgEngagementTime,
            avgArticleEngagementTime: ga4Data.avgArticleEngagementTime,
            returnRate: ga4Data.returnRate,
            avgScrollDepth: '-',
          },
          conversion: {
            microCvCount: 0,
          },
        },
      };

      // 3. Generate HTML
      const html = await generateHtmlReport(reportData);
      const filePath = await saveExportFile(html, 'report.html');

      Logger.success(`Management Design Sheet report generated: ${filePath}`);
    } catch (error) {
      Logger.error(`Failed to generate report: ${error instanceof Error ? error.message : String(error)}`);
      process.exit(1);
    }
  });
