import fs from 'fs/promises';
import path from 'path';
import { BlogStats } from '../types';
import { Logger } from '../utils/logger';

/**
 * Formats and writes the blog statistics to a TypeScript file.
 */
export async function deliverStats(stats: BlogStats, outputPath: string): Promise<void> {
  const fileContent = `/**
 * GENERATED BY BLOG-FACTORY - DO NOT EDIT DIRECTLY
 */
export const BLOG_STATS = ${JSON.stringify(stats, null, 2)} as const;
`;

  try {
    const dir = path.dirname(outputPath);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(outputPath, fileContent, 'utf-8');
    Logger.success(`Blog stats delivered to: ${outputPath}`);
  } catch (error) {
    throw new Error(`Failed to deliver stats to ${outputPath}: ${error instanceof Error ? error.message : String(error)}`);
  }
}
